DROP DATABASE IF EXISTS victorho_fryfteats_db;
CREATE DATABASE victorho_fryfteats_db;
USE victorho_fryfteats_db;

CREATE TABLE users (
    user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE restaurants (
    restaurant_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    cuisine VARCHAR(255),
    rating DOUBLE,
    price VARCHAR(255),
    url VARCHAR(255),
    image_url VARCHAR(255)
);

CREATE TABLE favorites (
    user_id INT NOT NULL,
    restaurant_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(restaurant_id)
);

INSERT INTO users (username, password, email) VALUES ("victorho", "password", "victorho@usc.edu");

INSERT INTO restaurants (name, address, phone_number, cuisine, rating, price, url, image_url)
VALUES 
('Little Pan - Los Angeles', '3742 S Figueroa St, Los Angeles, CA 90007', '(213) 364-1345', 'Dim Sum', 5, '$$', 'https://www.yelp.com/biz/little-pan-los-angeles-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/8rB3CtfUtZKEvfng-N9TVw/o.jpg'),
('Honeybird', '3201 S Hoover St, Ste 1835, Los Angeles, CA 90007', '(213) 536-5790', 'Southern, Chicken Shop, Desserts', 4, '$$', 'https://www.yelp.com/biz/honeybird-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media3.fl.yelpcdn.com/bphoto/XE9BrWmvSc0XCBIzfxfppg/o.jpg'),
('Cafe Mukbang', '3619 S Vermont Ave, Los Angeles, CA 90007', '(213) 205-8961', 'Korean, Asian Fusion, Japanese', 4.5, '$$', 'https://www.yelp.com/biz/cafe-mukbang-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/dFV3epzh6Du2FqkBNuf3OQ/o.jpg'),
('KOBUNGA', '929 W Jefferson Blvd, Ste 1610, Los Angeles, CA 90089', '(213) 536-5886', 'Korean, Barbeque', 4.5, '$$', 'https://www.yelp.com/biz/kobunga-los-angeles-3?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/y2LZonA6FEoquR_Bevs74w/o.jpg'),
('CAVA', '3201 S Hoover St, Ste 1840, Los Angeles, CA 90089', '(213) 212-9838', 'Mediterranean, Salad', 4, '$$', 'https://www.yelp.com/biz/cava-los-angeles-4?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/cpYEplZg_S2k_DhOhLMvsQ/o.jpg'),
('Dulce', '3096 McClintock Ave, Ste 1420, Los Angeles, CA 90007', '(213) 536-5609', 'Coffee & Tea, Salad, Donuts', 4, '$', 'https://www.yelp.com/biz/dulce-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/Kkut-lB_GYhJOSBvhvpPqg/o.jpg'),
('Holbox', '3655 S Grand Ave, Ste C9, Los Angeles, CA 90007', '(213) 986-9972', 'Latin American, Seafood, Mexican', 5, '$$', 'https://www.yelp.com/biz/holbox-los-angeles-2?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/f8OuY7bBbjY-rLR6qrC0lA/o.jpg'),
('Il Giardino', '3201 S Hoover St, Los Angeles, CA 90089', '(213) 536-5773', 'Italian, Salad, Sandwiches', 4, '$$', 'https://www.yelp.com/biz/il-giardino-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media3.fl.yelpcdn.com/bphoto/ryLxiBZ_vkhC_02YdTcSeQ/o.jpg'),
('City Tacos', '835 W Jefferson Blvd, Ste 1735, Los Angeles, CA 90089', '(213) 536-5203', 'Mexican', 4, '$', 'https://www.yelp.com/biz/city-tacos-los-angeles-2?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/7ur4a6bMR8t3GdnBCubbmA/o.jpg'),
('El Huero', '3000 S Figueroa St, Los Angeles, CA 90007', '(213) 747-0012', 'Mexican, Food Stands', 4, '$$', 'https://www.yelp.com/biz/el-huero-los-angeles-2?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/Mkvtu2BPmYgbVc70zvLW0Q/o.jpg'),
('Hart House - University Park South', '3726 S Figueroa St, Los Angeles, CA 90007', '(213) 510-1700', 'Burgers, Sandwiches, Salad', 4.5, '$$', 'https://www.yelp.com/biz/hart-house-university-park-south-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media4.fl.yelpcdn.com/bphoto/n7PU76fxHTCeZDX9960fpw/o.jpg'),
('Chinese Street Food', '3201 S Hoover St, Ste 1870, Los Angeles, CA 90089', '(213) 536-5161', 'Chinese', 3.5, '$$', 'https://www.yelp.com/biz/chinese-street-food-los-angeles-4?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/j0F-IR1v20f4zYRf2qnjag/o.jpg'),
('Dirt Dog', '2528 S Figueroa St, Los Angeles, CA 90007', '(213) 749-1813', 'Hot Dogs, Beer Bar', 4.5, '$$', 'https://www.yelp.com/biz/dirt-dog-los-angeles-4?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media3.fl.yelpcdn.com/bphoto/EPepO4WcY7X_q98Ttt7yqg/o.jpg'),
('FIG\'s Corner', '3009 S Figueroa St, Los Angeles, CA 90007', '(213) 441-7400', 'Asian Fusion', 4, '$$', 'https://www.yelp.com/biz/figs-corner-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/G3pB5WwPUMStW1Mod-yOvA/o.jpg'),
('Chichen Itza Restaurant', '3655 S Grand Ave, Ste C6, Los Angeles, CA 90007', '(213) 741-1075', 'Mexican, Sandwiches, Soup', 4.5, '$$', 'https://www.yelp.com/biz/chichen-itza-restaurant-los-angeles-3?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media3.fl.yelpcdn.com/bphoto/U8AGFYHKqjle9P9lYAmNww/o.jpg'),
('Himalayan House', '1277 W Jefferson Blvd, Los Angeles, CA 90007', '(323) 766-9775', 'Indian, Himalayan/Nepalese', 4, '$$', 'https://www.yelp.com/biz/himalayan-house-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/t4uQyPIEdTU1b__7yFGFjQ/o.jpg'),
('Pizza Please', '835 West Jefferson Blvd, Los Angeles, CA 90089', '(213) 536-5061', 'Pizza', 4.5, '$$', 'https://www.yelp.com/biz/pizza-please-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/Ue6tGfkHhWAPhSoVmeGp_g/o.jpg'),
('California Hot Chicken', '3335 S Figueroa St, Los Angeles, CA 90007', '(213) 536-5194', 'Chicken Shop', 4, '$$', 'https://www.yelp.com/biz/california-hot-chicken-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/QHYTv2_oTqoe2LV_oqDwaw/o.jpg'),
('Northern Cafe', '2904 S Figueroa St, Los Angeles, CA 90007', '(213) 741-9050', 'Noodles, Chinese', 4, '$$', 'https://www.yelp.com/biz/northern-cafe-los-angeles-6?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media3.fl.yelpcdn.com/bphoto/3wRN8liDI3eHZS0hCXosdQ/o.jpg'),
('Stout Burgers & Beers', '835 W Jefferson Blvd, Ste 1710, Los Angeles, CA 90089', '(213) 536-5058', 'Burgers, New American, Breakfast & Brunch', 4, '$$', 'https://www.yelp.com/biz/stout-burgers-and-beers-los-angeles-5?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media4.fl.yelpcdn.com/bphoto/RqLUHzsdAFearlpBsdF39g/o.jpg'),
('Greenleaf Kitchen and Cocktails', '929 W Jefferson Blvd, Ste 1650, Los Angeles, CA 90007', '', 'New American, Breakfast & Brunch, Salad', 3.5, '$$', 'https://www.yelp.com/biz/greenleaf-kitchen-and-cocktails-los-angeles-2?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media4.fl.yelpcdn.com/bphoto/e1rnZ3pUT_sL3-NSgJawWA/o.jpg'),
('Monarca Pasta & Grill', '2703 S Vermont Ave, Los Angeles, CA 90007', '(323) 731-8149', 'Italian', 4.5, '$', 'https://www.yelp.com/biz/monarca-pasta-and-grill-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media4.fl.yelpcdn.com/bphoto/_JeHvuRgTTSPItkragahIg/o.jpg'),
('Bird\'s Nest Cafe', '2403 S Vermont Ave, Los Angeles, CA 90007', '(323) 641-7986', 'Cafes, Breakfast & Brunch, Burgers', 4, '$$', 'https://www.yelp.com/biz/birds-nest-cafe-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/liYyKDn901UrwkfE0lgFUw/o.jpg'),
('Ono Hawaiian BBQ', '3010 S Figueroa St, Los Angeles, CA 90007', '(213) 745-9888', 'Barbeque, Hawaiian', 3, '$$', 'https://www.yelp.com/biz/ono-hawaiian-bbq-los-angeles-10?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/mY4S6pw4eoWbiBn5A1AoAw/o.jpg'),
('Figueroa Philly Cheese Steak', '358 W 38th St, Los Angeles, CA 90037', '(323) 448-0207', 'Cheesesteaks, Sandwiches, New American', 4, '$$', 'https://www.yelp.com/biz/figueroa-philly-cheese-steak-los-angeles-2?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media4.fl.yelpcdn.com/bphoto/ILYODtu73E4q8juFxqTkAQ/o.jpg'),
('Caveman Kitchen', '2215 S Vermont Ave, Ste 101, Los Angeles, CA 90007', '(323) 737-3717', 'Latin American, Burgers, Peruvian', 4, '$$', 'https://www.yelp.com/biz/caveman-kitchen-los-angeles-2?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/-7GEf0pdipnkrRxv_4bnlQ/o.jpg'),
('Chop Chop Chicken', '2526 S Figueroa St, Los Angeles, CA 90007', '(213) 536-5113', 'Asian Fusion, Mediterranean, Salad', 4.5, '$$', 'https://www.yelp.com/biz/chop-chop-chicken-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/lE5bFL0VMAAT03XhPBfhUw/o.jpg'),
('Ramen Kenjo', '929 W Jefferson Blvd, Ste 1630, Los Angeles, CA 90089', '(213) 536-5922', 'Ramen, Noodles, Soup', 4, '$$', 'https://www.yelp.com/biz/ramen-kenjo-los-angeles-2?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/gi61UpIxhU_BUjXSG1pQZA/o.jpg'),
('Thai By Trio', '2700 S Figueroa St, Ste 101, Los Angeles, CA 90007', '(213) 536-5699', 'Thai', 4, '$$', 'https://www.yelp.com/biz/thai-by-trio-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media4.fl.yelpcdn.com/bphoto/ueNX0QLv4DDepqELUuErPA/o.jpg'),
('Everytable', '1101 W 23rd St, University Park, CA 90007', '(760) 249-2026', 'Salad, Fast Food, Sandwiches', 4.5, '$', 'https://www.yelp.com/biz/everytable-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media3.fl.yelpcdn.com/bphoto/_nXRruiD7InYJMWFBlx09A/o.jpg'),
('Momota Ramen House', '3019 S Figueroa St, Los Angeles, CA 90007', '(213) 973-5488', 'Ramen', 4, '$$', 'https://www.yelp.com/biz/momota-ramen-house-los-angeles-8?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media3.fl.yelpcdn.com/bphoto/TCzdtTAP-1t9hdIz1P7Pqg/o.jpg'),
('Ebaes', '2314 S Union Ave, Los Angeles, CA 90007', '(213) 747-6888', 'Ramen, Asian Fusion, Sushi Bars', 4, '$$', 'https://www.yelp.com/biz/ebaes-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media4.fl.yelpcdn.com/bphoto/WbAcFa_4k4R2QYbOvxeutQ/o.jpg'),
('La Chuperia', '3742 S. Flower St., Los Angeles, CA 90007', '(213) 677-2388', 'Mexican, Bars', 4.5, '$$', 'https://www.yelp.com/biz/la-chuperia-los-angeles-15?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/pxSyLY8s9H0q7QKBQlddHg/o.jpg'),
('Trimana', '700 Exposition Park Dr, Los Angeles, CA 90037', '(213) 748-1226', 'Mexican, Burgers, Pizza', 4, '$', 'https://www.yelp.com/biz/trimana-los-angeles-54?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media3.fl.yelpcdn.com/bphoto/IL3NeIdzgddiTK6V0O9qQQ/o.jpg'),
('Chick-fil-A', '3758 S Figueroa St, Los Angeles, CA 90007', '(213) 747-8721', 'Fast Food, Chicken Shop, Salad', 3.5, '$$', 'https://www.yelp.com/biz/chick-fil-a-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/fEzJJDanwBmgsI1KA8UvQg/o.jpg'),
('La Pupusa Urban Eatery', '1051 W Washington Blvd, Ste G, Los Angeles, CA 90015', '(213) 749-4573', 'Salvadoran', 4.5, '$$', 'https://www.yelp.com/biz/la-pupusa-urban-eatery-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media3.fl.yelpcdn.com/bphoto/L2FX2aLQDvV5Z9a38klH6g/o.jpg'),
('Trojan Farmer\'s Market', '3551 Trousdale Pkwy, Los Angeles, CA 90089', '(213) 740-2311', 'Farmers Market', 4, '$', 'https://www.yelp.com/biz/trojan-farmers-market-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media3.fl.yelpcdn.com/bphoto/nnfn0jO0aEIl5kumRjlh4A/o.jpg'),
('Food-Truck Man', '1057-1199 W Jefferson Blvd, Los Angeles, CA 90007', '(202) 999-6689', 'Food Trucks', 4, '$$', 'https://www.yelp.com/biz/food-truck-man-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/llCoXwbspJoYlvbyCp2McA/o.jpg'),
('Cup O\' Joy', '3016 S Figueroa St, Los Angeles, CA 90007', '(213) 745-8569', 'Coffee & Tea, Taiwanese, Bubble Tea', 4, '$', 'https://www.yelp.com/biz/cup-o-joy-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media4.fl.yelpcdn.com/bphoto/qhPWyhLVSk9xb4TOm7avcA/o.jpg'),
('Rock and Reilly\'s USC Village', '3201 S Hoover St, Ste 1810, Los Angeles, CA 90007', '(213) 566-8660', 'Sports Bars, Gastropubs, Irish Pub', 3.5, '$$', 'https://www.yelp.com/biz/rock-and-reillys-usc-village-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media3.fl.yelpcdn.com/bphoto/8HPUH6O3i9QpOdrJbFHrMQ/o.jpg'),
('Gusina Saraba', '3655 S Grand Ave, Los Angeles, CA 90007', '(213) 441-7252', 'Desserts, Seafood', 4.5, '$$', 'https://www.yelp.com/biz/gusina-saraba-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media4.fl.yelpcdn.com/bphoto/Tz7Xqt6RTxmyR5rpqyJcXA/o.jpg'),
('Birds Nest Cafe', '2106 S Olive St, Los Angeles, CA 90007', '(213) 536-5676', 'Cafes, Breakfast & Brunch, Burgers', 4, '$$', 'https://www.yelp.com/biz/birds-nest-cafe-los-angeles-3?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/mE6qhAnZiu2kwlbti2P0TA/o.jpg'),
('Central Kitchen', '325 W Adams Blvd, Los Angeles, CA 90007', '(213) 908-2400', 'Burgers, Pizza, Breakfast & Brunch', 4, '$$', 'https://www.yelp.com/biz/central-kitchen-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media3.fl.yelpcdn.com/bphoto/8Dc6dfP1_8UXnEjKrb46wg/o.jpg'),
('Detroit Pizza Depot', '358 W 38th St, Unit 13, Los Angeles, CA 90037', '(909) 978-7383', 'Pizza', 4.5, '$$', 'https://www.yelp.com/biz/detroit-pizza-depot-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/shsUVUEZMeQBXOpuVZYywQ/o.jpg'),
('Monty’s Chicken & Waffles', '358 W 38th St, Los Angeles, CA 90037', '(323) 448-0207', 'Waffles, Sandwiches, Chicken Shop', 4, '$$', 'https://www.yelp.com/biz/monty-s-chicken-and-waffles-los-angeles?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media1.fl.yelpcdn.com/bphoto/plcSl380WfMPjxQSzeUalQ/o.jpg'),
('Nature\'s Brew', '2316 S Union Ave, Los Angeles, CA 90007', '(213) 741-9393', 'Coffee & Tea, Sandwiches, Breakfast & Brunch', 4, '$$', 'https://www.yelp.com/biz/natures-brew-los-angeles-3?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/siVRepnE8CjFQMt_KhIecw/o.jpg'),
('Pasta Roma', '2827 S Figueroa St, Los Angeles, CA 90007', '(213) 742-0303', 'Italian, Pizza, Sandwiches', 3.5, '$$', 'https://www.yelp.com/biz/pasta-roma-los-angeles-2?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media4.fl.yelpcdn.com/bphoto/XcXQVzOFdyFLJyOtG_qtFA/o.jpg'),
('Study Hall', '2827 S Hoover St, Los Angeles, CA 90007', '(213) 677-2550', 'Gastropubs, Burgers, Sandwiches', 4, '$$', 'https://www.yelp.com/biz/study-hall-los-angeles-3?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/KYiZ7CT3N8lk9Yn9gfUSjA/o.jpg'),
('Blaze Pizza', '3335 S Figueroa St, Los Angeles, CA 90007', '(213) 814-2485', 'Salad, Pizza, Fast Food', 3.5, '$$', 'https://www.yelp.com/biz/blaze-pizza-los-angeles-6?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/3SF4gdGlpeg8PDrKGIQGEQ/o.jpg'),
('Qwench Juice Bar', '2595 S Hoover St, Los Angeles, CA 90007', '(213) 625-1345', 'Juice Bars & Smoothies, Salad, Acai Bowls', 4, '$$', 'https://www.yelp.com/biz/qwench-juice-bar-los-angeles-15?adjust_creative=HcTws1zsDWAeEmQWEvZw5g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=HcTws1zsDWAeEmQWEvZw5g', 'https://s3-media2.fl.yelpcdn.com/bphoto/v-yvSf2bSp14yPUpOfqMuQ/o.jpg');

INSERT INTO favorites (user_id, restaurant_id) VALUES (1, 5);
INSERT INTO favorites (user_id, restaurant_id) VALUES (1, 6);
